class Jjr < Formula
  desc "Local terminal review surface for jj stacks generated by an agent"
  homepage "https://github.com/ericbmerritt/local-review"
  url "https://github.com/ericbmerritt/local-review/archive/refs/tags/v0.1.3.tar.gz"
  sha256 "79318057ca76dc691e72da46e19e96a02b51bd791781c984807939e56cd79d2e"
  license any_of: ["MIT", "Apache-2.0"]
  head "https://github.com/ericbmerritt/local-review.git", branch: "main"

  depends_on "rust" => :build
  depends_on "jj"

  def install
    system "cargo", "install", *std_cargo_args(path: "crates/jjr")
  end

  test do
    assert_match "jjr", shell_output("#{bin}/jjr --version")
  end
end
