class Jjr < Formula
  desc "Local terminal review surface for jj stacks generated by an agent"
  homepage "https://github.com/ericbmerritt/jujutsu-review"
  url "https://github.com/ericbmerritt/jujutsu-review/archive/refs/tags/v0.1.0.tar.gz"
  # TODO: replace with the real sha256 once v0.1.0 is tagged. Run:
  #   curl -sL https://github.com/ericbmerritt/jujutsu-review/archive/refs/tags/v0.1.0.tar.gz | shasum -a 256
  # From v0.2.0 onward, the `bump-formula` workflow in the source repo
  # updates `url` + `sha256` automatically on every tag.
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license any_of: ["MIT", "Apache-2.0"]
  head "https://github.com/ericbmerritt/jujutsu-review.git", branch: "main"

  depends_on "rust" => :build
  depends_on "jj"

  def install
    system "cargo", "install", *std_cargo_args(path: ".")
  end

  test do
    assert_match "jjr", shell_output("#{bin}/jjr --version")
  end
end
